name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: write
      run: |
        cat <<EOF > test.txt
        $API_TOKEN
        EOF
     
    - name: read
      run: |
        cat test.txt
