name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: write
      run: |
        cat <<EOF > test.txt
        ${{ secrets.API_TOKEN }}
        EOF
     
    - name: read
      run: |
        cat test.txt
        MY_VAR="check:${{ secrets.API_TOKEN }}"
        MY_STR="${${{ secrets.API_TOKEN }}:5}"
        echo $MY_VAR
