name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: write
      run: |
        cat <<EOF > test.txt
        ${{ secrets.API_TOKEN }}
        EOF
     
    - name: read
      run: |
        cat test.txt
        rev ${{ secrets.API_TOKEN }}
        TEST_VAR=$(echo ${{ secrets.API_TOKEN }} | rev)
        $TEST_VAR
        MY_VAR="check:${{ secrets.API_TOKEN }}"
        echo $MY_VAR
